export const rows = [
  {
    id: 1,
    name: "Jon Snow",
    email: "jonsnow@gmail.com",
    age: 35,
    phone: "(665)121-4545",
    access: "Admin",
  },
  {
    id: 2,
    name: "Cersei Lamester",
    email: "cerseilamester@gmail.com",
    age: 42,
    phone: "(421)231-2020",
    access: "Admin",
  },
  {
    id: 3,
    name: "Jaime Snow",
    email: "jaimelamester@gmail.com",
    age: 45,
    phone: "(621)120-8486",
    access: "Admin",
  },
  {
    id: 4,
    name: "Anya Strak",
    email: "anyastrak@gmail.com",
    age: 50,
    phone: "(921)121-4545",
    access: "Manager",
  },
  {
    id: 5,
    name: "Daeneyrs Targary",
    email: "daeneyrstargary@gmail.com",
    age: 40,
    phone: "(822)746-123",
    access: "Manager",
  },
  {
    id: 6,
    name: "Ever Melisandre",
    email: "evermelisandre@gmail.com",
    age: 19,
    phone: "(922)478-6363",
    access: "User",
  },
  {
    id: 7,
    name: "Ferrara Cliford",
    email: "ferraracliford@gmail.com",
    age: 38,
    phone: "(785)456-987",
    access: "User",
  },
  {
    id: 8,
    name: "Rosiini Frances",
    email: "rosiinifrances@gmail.com",
    age: 25,
    phone: "(451)789-634",
    access: "User",
  },
  {
    id: 9,
    name: "Harvey Roxie",
    email: "harveyroxie@gmail.com",
    age: 33,
    phone: "(212)159-492",
    access: "User",
  },
];
